/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package temporal.test

import io.temporal.testing.TestWorkflowEnvironment
import io.temporal.testing.TestWorkflowExtension
import io.temporal.worker.Worker
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.RegisterExtension

class SimpleWorkflowTest {
    @RegisterExtension
    private val testWorkflowExt = TestWorkflowExtension.newBuilder()
        .setWorkflowTypes(SimpleWorkflowImpl::class.java)
        .setActivityImplementations(SimpleActivitiesImpl())
        .setDoNotStart(true)
        .build()

    @Test
    fun testSimpleWorkflow(
        testEnv: TestWorkflowEnvironment,
        worker: Worker,
        workflow: ISimpleWorkflow
    ) {
        // Start test environment
        testEnv.start()

        val res = workflow.execute( "prescriptionCreatedEvent")
        Assertions.assertNotNull(res)
    }
}
